language: python
python:
  - 3.9
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - pytest libpythonpro_lu1zibrahim --cov=libpythonpro_lu1zibrahim
  - flake8
after_success:
  - codecov