language: python
python:
  - 3.9
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro-lu1zibrahim --cov=libpythonpro-lu1zibrahim
after_success:
  - codecov